<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ReservationCancellation">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Username" type="xs:string" minOccurs="1" maxOccurs="1" default="username" xmlns:doc="Customer's username"/>
        <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1" default="password" xmlns:doc="Customer's password"/>
        <xs:element name="ReservationID" type="xs:int" minOccurs="1" maxOccurs="1" default="1" xmlns:doc="The ID of the reservation."/>
        <xs:element name="DetailID" type="xs:int" minOccurs="0" maxOccurs="1"  xmlns:doc="The ID of the single detail (or service) that you wish to cancel."/>
        <xs:element name="Remarks" type="xs:string" minOccurs="0" maxOccurs="1"  xmlns:doc="Any remarks related to the cancellation of this reservation."/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>