<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="ExcursionDescription">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Username" type="xs:string" minOccurs="1" maxOccurs="1" default="username" xmlns:doc="Customer's username"/>
        <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1" default="password" xmlns:doc="Customer's password" />
        <xs:element name="ExcursionID" type="xs:int" minOccurs="1" maxOccurs="1" default="1" xmlns:doc="The excursion that will be returned "/>
        <xs:element name="Language" minOccurs="0" maxOccurs="1" default="en" xmlns:doc="2 character string that specifies your chosen language.">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="en|de|fr|zh|nl" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>