<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="SearchPriceZones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Username" type="xs:string" minOccurs="1" maxOccurs="1" default="username" xmlns:doc="Customer's username"/>
        <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1" default="password" xmlns:doc="Customer's password"/>
        <xs:element name="StationID" type="xs:int" minOccurs="0" maxOccurs="1"  xmlns:doc="Filter by Station ID">
          <xs:annotation>
            <xs:documentation>
              See PlaceSearch for information on how to obtain these IDs
            </xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>