<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="OfferListRequest">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Username" type="xs:string" minOccurs="1" maxOccurs="1" default="demouser" xmlns:doc="Customer's username"/>
        <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1" default="#resuomed*" xmlns:doc="Customer's password" />
        <xs:element name="HotelID" type="xs:int" minOccurs="0" maxOccurs="1" default="495" xmlns:doc="Show offers for a specific hotel "/>
        <xs:element name="ContractID" type="xs:int" minOccurs="0" maxOccurs="1" default="135" xmlns:doc="Show offers for a specific contract"/>
        <xs:element name="UseTariff" type="xs:boolean" minOccurs="0" maxOccurs="1" default="true" xmlns:doc="When true, returns offers based on your assigned tariff. When false, will return based on your own contracts."/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>