//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace HotelsSearchResponse {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SearchHotels {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.DateTime dateFromField;
        
        private System.DateTime dateToField;
        
        private RoomType[] roomsField;
        
        private string languageField;
        
        private string boardField;
        
        private int hotelIDField;
        
        private bool hotelIDFieldSpecified;
        
        private string hotelNameField;
        
        private string roomNameField;
        
        private SearchHotelsHoteltype hoteltypeField;
        
        private bool hoteltypeFieldSpecified;
        
        private int locationField;
        
        private bool locationFieldSpecified;
        
        private int ratingField;
        
        private bool ratingFieldSpecified;
        
        private string countryField;
        
        private int provinceField;
        
        private bool provinceFieldSpecified;
        
        private int prefectureField;
        
        private bool prefectureFieldSpecified;
        
        private int cityField;
        
        private bool cityFieldSpecified;
        
        private bool useTariffField;
        
        private bool useTariffFieldSpecified;
        
        private bool isOptimizedField;
        
        private bool isOptimizedFieldSpecified;
        
        private ResponseSchema responseField;
        
        private ErrorListSchema errorListField;
        
        public SearchHotels() {
            this.languageField = "en";
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Room", IsNullable=false)]
        public RoomType[] Rooms {
            get {
                return this.roomsField;
            }
            set {
                this.roomsField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public string Board {
            get {
                return this.boardField;
            }
            set {
                this.boardField = value;
            }
        }
        
        /// <remarks/>
        public int HotelID {
            get {
                return this.hotelIDField;
            }
            set {
                this.hotelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HotelIDSpecified {
            get {
                return this.hotelIDFieldSpecified;
            }
            set {
                this.hotelIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string HotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
            }
        }
        
        /// <remarks/>
        public string RoomName {
            get {
                return this.roomNameField;
            }
            set {
                this.roomNameField = value;
            }
        }
        
        /// <remarks/>
        public SearchHotelsHoteltype Hoteltype {
            get {
                return this.hoteltypeField;
            }
            set {
                this.hoteltypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoteltypeSpecified {
            get {
                return this.hoteltypeFieldSpecified;
            }
            set {
                this.hoteltypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationSpecified {
            get {
                return this.locationFieldSpecified;
            }
            set {
                this.locationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RatingSpecified {
            get {
                return this.ratingFieldSpecified;
            }
            set {
                this.ratingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public int Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProvinceSpecified {
            get {
                return this.provinceFieldSpecified;
            }
            set {
                this.provinceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Prefecture {
            get {
                return this.prefectureField;
            }
            set {
                this.prefectureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrefectureSpecified {
            get {
                return this.prefectureFieldSpecified;
            }
            set {
                this.prefectureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CitySpecified {
            get {
                return this.cityFieldSpecified;
            }
            set {
                this.cityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool UseTariff {
            get {
                return this.useTariffField;
            }
            set {
                this.useTariffField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseTariffSpecified {
            get {
                return this.useTariffFieldSpecified;
            }
            set {
                this.useTariffFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsOptimized {
            get {
                return this.isOptimizedField;
            }
            set {
                this.isOptimizedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsOptimizedSpecified {
            get {
                return this.isOptimizedFieldSpecified;
            }
            set {
                this.isOptimizedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ResponseSchema Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public ErrorListSchema ErrorList {
            get {
                return this.errorListField;
            }
            set {
                this.errorListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoomType {
        
        private int adultsField;
        
        private int childrenField;
        
        private string childrenAgesField;
        
        public RoomType() {
            this.childrenField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Adults {
            get {
                return this.adultsField;
            }
            set {
                this.adultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ChildrenAges {
            get {
                return this.childrenAgesField;
            }
            set {
                this.childrenAgesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ErrorListSchema {
        
        private string[] errorsField;
        
        private string[] warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Error", IsNullable=false)]
        public string[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Warning", IsNullable=false)]
        public string[] Warnings {
            get {
                return this.warningsField;
            }
            set {
                this.warningsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RoomPriceSchema {
        
        private decimal discountField;
        
        private decimal valueField;
        
        /// <remarks/>
        public decimal Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResponseSchema {
        
        private ResponseSchemaHotels hotelsField;
        
        /// <remarks/>
        public ResponseSchemaHotels Hotels {
            get {
                return this.hotelsField;
            }
            set {
                this.hotelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotels {
        
        private ResponseSchemaHotelsHotel[] hotelField;
        
        private ResponseSchemaHotelsResults resultsField;
        
        private int recordsField;
        
        private bool recordsFieldSpecified;
        
        private int overnightsField;
        
        private int numberOfRoomsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Hotel")]
        public ResponseSchemaHotelsHotel[] Hotel {
            get {
                return this.hotelField;
            }
            set {
                this.hotelField = value;
            }
        }
        
        /// <remarks/>
        public ResponseSchemaHotelsResults Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecordsSpecified {
            get {
                return this.recordsFieldSpecified;
            }
            set {
                this.recordsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Overnights {
            get {
                return this.overnightsField;
            }
            set {
                this.overnightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NumberOfRooms {
            get {
                return this.numberOfRoomsField;
            }
            set {
                this.numberOfRoomsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsHotel {
        
        private string nameField;
        
        private string imageThumbURLField;
        
        private string countryField;
        
        private int stateField;
        
        private bool stateFieldSpecified;
        
        private string stateProvinceNameField;
        
        private int prefectureField;
        
        private bool prefectureFieldSpecified;
        
        private string prefectureNameField;
        
        private int cityField;
        
        private bool cityFieldSpecified;
        
        private string cityNameField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private decimal ratingField;
        
        private bool ratingFieldSpecified;
        
        private decimal longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private decimal latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private int typeField;
        
        private bool typeFieldSpecified;
        
        private string typeDescriptionField;
        
        private int locationField;
        
        private bool locationFieldSpecified;
        
        private string locationDescriptionField;
        
        private string officialRatingField;
        
        private string descriptionField;
        
        private decimal lowRateField;
        
        private bool lowRateFieldSpecified;
        
        private bool specialOfferField;
        
        private bool specialOfferFieldSpecified;
        
        private int travelAdvisorField;
        
        private bool travelAdvisorFieldSpecified;
        
        private int availabilityField;
        
        private bool availabilityFieldSpecified;
        
        private decimal lowestPriceField;
        
        private bool lowestPriceFieldSpecified;
        
        private int officialRating_IDField;
        
        private bool officialRating_IDFieldSpecified;
        
        private int property_Class_IDField;
        
        private bool property_Class_IDFieldSpecified;
        
        private bool hasAllInclusiveField;
        
        private bool hasAllInclusiveFieldSpecified;
        
        private bool hasContinentalBreakfastField;
        
        private bool hasContinentalBreakfastFieldSpecified;
        
        private bool hasIndoorPoolField;
        
        private bool hasIndoorPoolFieldSpecified;
        
        private bool hasOutdoorPoolField;
        
        private bool hasOutdoorPoolFieldSpecified;
        
        private bool hasDataPortsField;
        
        private bool hasDataPortsFieldSpecified;
        
        private bool hasFitnessFacilityField;
        
        private bool hasFitnessFacilityFieldSpecified;
        
        private bool hasSPAWellnessCentreField;
        
        private bool hasSPAWellnessCentreFieldSpecified;
        
        private bool hasPetsAllowedField;
        
        private bool hasPetsAllowedFieldSpecified;
        
        private bool hasParkingGarageField;
        
        private bool hasParkingGarageFieldSpecified;
        
        private ResponseSchemaHotelsHotelRooms roomsField;
        
        private int idField;
        
        private int giata_idField;
        
        private string currencyField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string ImageThumbURL {
            get {
                return this.imageThumbURLField;
            }
            set {
                this.imageThumbURLField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string StateProvinceName {
            get {
                return this.stateProvinceNameField;
            }
            set {
                this.stateProvinceNameField = value;
            }
        }
        
        /// <remarks/>
        public int Prefecture {
            get {
                return this.prefectureField;
            }
            set {
                this.prefectureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrefectureSpecified {
            get {
                return this.prefectureFieldSpecified;
            }
            set {
                this.prefectureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string PrefectureName {
            get {
                return this.prefectureNameField;
            }
            set {
                this.prefectureNameField = value;
            }
        }
        
        /// <remarks/>
        public int City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CitySpecified {
            get {
                return this.cityFieldSpecified;
            }
            set {
                this.cityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string Address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        public decimal Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RatingSpecified {
            get {
                return this.ratingFieldSpecified;
            }
            set {
                this.ratingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TypeDescription {
            get {
                return this.typeDescriptionField;
            }
            set {
                this.typeDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationSpecified {
            get {
                return this.locationFieldSpecified;
            }
            set {
                this.locationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LocationDescription {
            get {
                return this.locationDescriptionField;
            }
            set {
                this.locationDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string OfficialRating {
            get {
                return this.officialRatingField;
            }
            set {
                this.officialRatingField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal LowRate {
            get {
                return this.lowRateField;
            }
            set {
                this.lowRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LowRateSpecified {
            get {
                return this.lowRateFieldSpecified;
            }
            set {
                this.lowRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool SpecialOffer {
            get {
                return this.specialOfferField;
            }
            set {
                this.specialOfferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SpecialOfferSpecified {
            get {
                return this.specialOfferFieldSpecified;
            }
            set {
                this.specialOfferFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int TravelAdvisor {
            get {
                return this.travelAdvisorField;
            }
            set {
                this.travelAdvisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TravelAdvisorSpecified {
            get {
                return this.travelAdvisorFieldSpecified;
            }
            set {
                this.travelAdvisorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailabilitySpecified {
            get {
                return this.availabilityFieldSpecified;
            }
            set {
                this.availabilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal LowestPrice {
            get {
                return this.lowestPriceField;
            }
            set {
                this.lowestPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LowestPriceSpecified {
            get {
                return this.lowestPriceFieldSpecified;
            }
            set {
                this.lowestPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int OfficialRating_ID {
            get {
                return this.officialRating_IDField;
            }
            set {
                this.officialRating_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OfficialRating_IDSpecified {
            get {
                return this.officialRating_IDFieldSpecified;
            }
            set {
                this.officialRating_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Property_Class_ID {
            get {
                return this.property_Class_IDField;
            }
            set {
                this.property_Class_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Property_Class_IDSpecified {
            get {
                return this.property_Class_IDFieldSpecified;
            }
            set {
                this.property_Class_IDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasAllInclusive {
            get {
                return this.hasAllInclusiveField;
            }
            set {
                this.hasAllInclusiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasAllInclusiveSpecified {
            get {
                return this.hasAllInclusiveFieldSpecified;
            }
            set {
                this.hasAllInclusiveFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasContinentalBreakfast {
            get {
                return this.hasContinentalBreakfastField;
            }
            set {
                this.hasContinentalBreakfastField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasContinentalBreakfastSpecified {
            get {
                return this.hasContinentalBreakfastFieldSpecified;
            }
            set {
                this.hasContinentalBreakfastFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasIndoorPool {
            get {
                return this.hasIndoorPoolField;
            }
            set {
                this.hasIndoorPoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasIndoorPoolSpecified {
            get {
                return this.hasIndoorPoolFieldSpecified;
            }
            set {
                this.hasIndoorPoolFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasOutdoorPool {
            get {
                return this.hasOutdoorPoolField;
            }
            set {
                this.hasOutdoorPoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasOutdoorPoolSpecified {
            get {
                return this.hasOutdoorPoolFieldSpecified;
            }
            set {
                this.hasOutdoorPoolFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasDataPorts {
            get {
                return this.hasDataPortsField;
            }
            set {
                this.hasDataPortsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasDataPortsSpecified {
            get {
                return this.hasDataPortsFieldSpecified;
            }
            set {
                this.hasDataPortsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasFitnessFacility {
            get {
                return this.hasFitnessFacilityField;
            }
            set {
                this.hasFitnessFacilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasFitnessFacilitySpecified {
            get {
                return this.hasFitnessFacilityFieldSpecified;
            }
            set {
                this.hasFitnessFacilityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasSPAWellnessCentre {
            get {
                return this.hasSPAWellnessCentreField;
            }
            set {
                this.hasSPAWellnessCentreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasSPAWellnessCentreSpecified {
            get {
                return this.hasSPAWellnessCentreFieldSpecified;
            }
            set {
                this.hasSPAWellnessCentreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasPetsAllowed {
            get {
                return this.hasPetsAllowedField;
            }
            set {
                this.hasPetsAllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasPetsAllowedSpecified {
            get {
                return this.hasPetsAllowedFieldSpecified;
            }
            set {
                this.hasPetsAllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool HasParkingGarage {
            get {
                return this.hasParkingGarageField;
            }
            set {
                this.hasParkingGarageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasParkingGarageSpecified {
            get {
                return this.hasParkingGarageFieldSpecified;
            }
            set {
                this.hasParkingGarageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ResponseSchemaHotelsHotelRooms Rooms {
            get {
                return this.roomsField;
            }
            set {
                this.roomsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int giata_id {
            get {
                return this.giata_idField;
            }
            set {
                this.giata_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsHotelRooms {
        
        private ResponseSchemaHotelsHotelRoomsRoom[] roomsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Room", IsNullable=false)]
        public ResponseSchemaHotelsHotelRoomsRoom[] Rooms {
            get {
                return this.roomsField;
            }
            set {
                this.roomsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsHotelRoomsRoom {
        
        private string nameField;
        
        private ResponseSchemaHotelsHotelRoomsRoomOccupancy[] occupancyField;
        
        private int idField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Occupancy")]
        public ResponseSchemaHotelsHotelRoomsRoomOccupancy[] Occupancy {
            get {
                return this.occupancyField;
            }
            set {
                this.occupancyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsHotelRoomsRoomOccupancy {
        
        private RoomPriceSchema rrField;
        
        private RoomPriceSchema bbField;
        
        private RoomPriceSchema hbField;
        
        private RoomPriceSchema fbField;
        
        private RoomPriceSchema aiField;
        
        private RoomPriceSchema uiField;
        
        private string codeField;
        
        private bool minLOSErrorField;
        
        private bool minLOSErrorFieldSpecified;
        
        private bool releaseErrorField;
        
        private bool releaseErrorFieldSpecified;
        
        private int availabilityField;
        
        private bool stopSalesField;
        
        private bool stopSalesFieldSpecified;
        
        private int contractIDField;
        
        private bool contractIDFieldSpecified;
        
        private int nonRefundableField;
        
        private bool nonRefundableFieldSpecified;
        
        /// <remarks/>
        public RoomPriceSchema RR {
            get {
                return this.rrField;
            }
            set {
                this.rrField = value;
            }
        }
        
        /// <remarks/>
        public RoomPriceSchema BB {
            get {
                return this.bbField;
            }
            set {
                this.bbField = value;
            }
        }
        
        /// <remarks/>
        public RoomPriceSchema HB {
            get {
                return this.hbField;
            }
            set {
                this.hbField = value;
            }
        }
        
        /// <remarks/>
        public RoomPriceSchema FB {
            get {
                return this.fbField;
            }
            set {
                this.fbField = value;
            }
        }
        
        /// <remarks/>
        public RoomPriceSchema AI {
            get {
                return this.aiField;
            }
            set {
                this.aiField = value;
            }
        }
        
        /// <remarks/>
        public RoomPriceSchema UI {
            get {
                return this.uiField;
            }
            set {
                this.uiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool MinLOSError {
            get {
                return this.minLOSErrorField;
            }
            set {
                this.minLOSErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinLOSErrorSpecified {
            get {
                return this.minLOSErrorFieldSpecified;
            }
            set {
                this.minLOSErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool ReleaseError {
            get {
                return this.releaseErrorField;
            }
            set {
                this.releaseErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReleaseErrorSpecified {
            get {
                return this.releaseErrorFieldSpecified;
            }
            set {
                this.releaseErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool StopSales {
            get {
                return this.stopSalesField;
            }
            set {
                this.stopSalesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StopSalesSpecified {
            get {
                return this.stopSalesFieldSpecified;
            }
            set {
                this.stopSalesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ContractID {
            get {
                return this.contractIDField;
            }
            set {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContractIDSpecified {
            get {
                return this.contractIDFieldSpecified;
            }
            set {
                this.contractIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int NonRefundable {
            get {
                return this.nonRefundableField;
            }
            set {
                this.nonRefundableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NonRefundableSpecified {
            get {
                return this.nonRefundableFieldSpecified;
            }
            set {
                this.nonRefundableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsResults {
        
        private int recordCountField;
        
        private ResponseSchemaHotelsResultsCityResult[] cityResultsField;
        
        private ResponseSchemaHotelsResultsFacilities facilitiesField;
        
        private ResponseSchemaHotelsResultsPropertyTypes propertyTypesField;
        
        private ResponseSchemaHotelsResultsStarRatings starRatingsField;
        
        /// <remarks/>
        public int RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CityResult", IsNullable=false)]
        public ResponseSchemaHotelsResultsCityResult[] CityResults {
            get {
                return this.cityResultsField;
            }
            set {
                this.cityResultsField = value;
            }
        }
        
        /// <remarks/>
        public ResponseSchemaHotelsResultsFacilities Facilities {
            get {
                return this.facilitiesField;
            }
            set {
                this.facilitiesField = value;
            }
        }
        
        /// <remarks/>
        public ResponseSchemaHotelsResultsPropertyTypes PropertyTypes {
            get {
                return this.propertyTypesField;
            }
            set {
                this.propertyTypesField = value;
            }
        }
        
        /// <remarks/>
        public ResponseSchemaHotelsResultsStarRatings StarRatings {
            get {
                return this.starRatingsField;
            }
            set {
                this.starRatingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsResultsCityResult {
        
        private int cityField;
        
        private string cityNameField;
        
        private int hotelsField;
        
        /// <remarks/>
        public int City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string CityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        public int Hotels {
            get {
                return this.hotelsField;
            }
            set {
                this.hotelsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsResultsFacilities {
        
        private int allInclusiveField;
        
        private int breakfastField;
        
        private int indoorPoolField;
        
        private int outdoorPoolField;
        
        private int internetServicesField;
        
        private int fitnessFacilityField;
        
        private int sPAWellnessCentreField;
        
        private int petsAllowedField;
        
        private int parkingField;
        
        /// <remarks/>
        public int AllInclusive {
            get {
                return this.allInclusiveField;
            }
            set {
                this.allInclusiveField = value;
            }
        }
        
        /// <remarks/>
        public int Breakfast {
            get {
                return this.breakfastField;
            }
            set {
                this.breakfastField = value;
            }
        }
        
        /// <remarks/>
        public int IndoorPool {
            get {
                return this.indoorPoolField;
            }
            set {
                this.indoorPoolField = value;
            }
        }
        
        /// <remarks/>
        public int OutdoorPool {
            get {
                return this.outdoorPoolField;
            }
            set {
                this.outdoorPoolField = value;
            }
        }
        
        /// <remarks/>
        public int InternetServices {
            get {
                return this.internetServicesField;
            }
            set {
                this.internetServicesField = value;
            }
        }
        
        /// <remarks/>
        public int FitnessFacility {
            get {
                return this.fitnessFacilityField;
            }
            set {
                this.fitnessFacilityField = value;
            }
        }
        
        /// <remarks/>
        public int SPAWellnessCentre {
            get {
                return this.sPAWellnessCentreField;
            }
            set {
                this.sPAWellnessCentreField = value;
            }
        }
        
        /// <remarks/>
        public int PetsAllowed {
            get {
                return this.petsAllowedField;
            }
            set {
                this.petsAllowedField = value;
            }
        }
        
        /// <remarks/>
        public int Parking {
            get {
                return this.parkingField;
            }
            set {
                this.parkingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsResultsPropertyTypes {
        
        private int hotelsField;
        
        private int apartmentsField;
        
        private int villasField;
        
        /// <remarks/>
        public int Hotels {
            get {
                return this.hotelsField;
            }
            set {
                this.hotelsField = value;
            }
        }
        
        /// <remarks/>
        public int Apartments {
            get {
                return this.apartmentsField;
            }
            set {
                this.apartmentsField = value;
            }
        }
        
        /// <remarks/>
        public int Villas {
            get {
                return this.villasField;
            }
            set {
                this.villasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ResponseSchemaHotelsResultsStarRatings {
        
        private int fiveStarsField;
        
        private int fourStarsField;
        
        private int threeStarsField;
        
        private int twoStarsField;
        
        /// <remarks/>
        public int FiveStars {
            get {
                return this.fiveStarsField;
            }
            set {
                this.fiveStarsField = value;
            }
        }
        
        /// <remarks/>
        public int FourStars {
            get {
                return this.fourStarsField;
            }
            set {
                this.fourStarsField = value;
            }
        }
        
        /// <remarks/>
        public int ThreeStars {
            get {
                return this.threeStarsField;
            }
            set {
                this.threeStarsField = value;
            }
        }
        
        /// <remarks/>
        public int TwoStars {
            get {
                return this.twoStarsField;
            }
            set {
                this.twoStarsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum SearchHotelsHoteltype {
        
        /// <remarks/>
        H,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        V,
        
        /// <remarks/>
        U,
    }
}
