<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="SearchTransferList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Username" type="xs:string" minOccurs="1" maxOccurs="1" default="username" xmlns:doc="Customer's username"/>
                <xs:element name="Password" type="xs:string" minOccurs="1" maxOccurs="1" default="password" xmlns:doc="Customer's password"/>
              <xs:element name="DateFrom" type="xs:date" minOccurs="1" maxOccurs="1" fixed="2020-06-01" xmlns:doc="The starting date you want to search from" />
                <xs:element name="DateTo" type="xs:date" minOccurs="1" maxOccurs="1"  fixed="2020-06-15" xmlns:doc="The end date you want to search to"/>
                <xs:element name="Reference" type="xs:string" minOccurs="0" maxOccurs="1" xmlns:doc="The reference number assigned to the reservation by the agent "/>
                <xs:element name="Name" type="xs:string" minOccurs="0" maxOccurs="1" xmlns:doc="The lead traveler’s name"/>
                <xs:element name="Accommodation" type="xs:string" minOccurs="0" maxOccurs="1" xmlns:doc="The name of the accommodation the transfer will be going to/from"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
