<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="PlaceDescription">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Response">
          <xs:complexType>
            <xs:choice>
              <xs:sequence>
                <xs:element name="City" type="Place">
                </xs:element>
              </xs:sequence>
              <xs:sequence>
                <xs:element name="Prefecture" type="Place">
                </xs:element>
              </xs:sequence>
              <xs:sequence>
                <xs:element name="StateProvince" type="Place">
                </xs:element>
              </xs:sequence>
            </xs:choice>
          </xs:complexType>
        </xs:element>
        <xs:element name="ErrorList" minOccurs="0" maxOccurs="1">
          <xs:complexType>
            <xs:all>
              <xs:element name="Errors" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="Error" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Warnings" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="Warning" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Place">
    <xs:sequence>
      <xs:element type="xs:string" name="Latitude" />
      <xs:element type="xs:string" name="Longitude"/>
      <xs:element type="xs:string" name="Name"/>
      <xs:element type="xs:string" name="Description"/>
      <xs:element name="Photos">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Photo" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element type="xs:string" name="Url" />
                </xs:sequence>
                <xs:attribute type="xs:boolean" name="IsDefault"/>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:int" name="Id"/>
  </xs:complexType>
</xs:schema>
